---
title: "import_clean_slim"
author: "Keith Hankowsky"
date: "3/28/2022"
output: html_document
---


```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(skimr)
library(data.table)
library(fuzzyjoin)
library(lubridate)
library(kableExtra)

library(maps) # land masses
library(rgdal) # read OGR vector maps into Spatial objects
library(viridis) # for customizing scale bars
library(mapproj)
library(hexbin)
library(sf)
library(scales)
library(beepr)
```


# Import Data
## Study fleet data
```{r}
#importing the study fleet data
study_fleet <- read_csv('./data/STUDY_FLEET_GROUNFISH_DATA_PULL_V1.csv')
```


## Observer data
```{r}
observer1 <- read_excel('./data/result1.xlsx')
observer2 <- read_excel('./data/result2.xlsx', col_names = FALSE)


observer_colnames <- as.vector(colnames(observer1))

names(observer2) <- observer_colnames


observer2 <- observer2 %>%
  mutate(PERMIT1 = as.logical(PERMIT1), 
         GIS_LATHBEG = as.double(GIS_LATHBEG), 
         GIS_LONHBEG = as.double(GIS_LONHBEG),
         GIS_LATHEND = as.double(GIS_LATHEND), 
         GIS_LONHEND = as.double(GIS_LONHEND), 
         NSWEEPS = as.logical(NSWEEPS), 
         SWEEPDIA = as.logical(SWEEPDIA), 
         LINERMSIZE = as.logical(LINERMSIZE), 
         CODMSIZE = as.logical(CODMSIZE),
         MARKET = as.logical(MARKET), 
         MSWGTAVG = as.double(MSWGTAVG), 
         SOAKDUR = as.double(SOAKDUR), 
         HAULDUR = as.double(HAULDUR), 
         HAILWT = as.double(HAILWT), 
         LIVE_WT = as.double(LIVE_WT)
         )

#bind the two sheets together
observer <- bind_rows(observer1, observer2)

#clear environment of unnecessary datasets
rm(observer1)
rm(observer2)
rm(observer_colnames)
```


## NEFSC survey data
```{r}
#importing and joining the spring nefsc survey catch and station data and joining them 
nefsc_station_spring <- read_csv('./data/22561_UNION_FSCS_SVSTA_spring.csv')

nefsc_catch_spring <- read_csv('./data/22561_UNION_FSCS_SVCAT_spring.csv')

nefsc_spring <- left_join(nefsc_station_spring, nefsc_catch_spring, 
                           by = c("ID", "CRUISE6", "STRATUM", "TOW", "STATION"))


#importing and joining the fall nefsc survey catch and station data and joining them 
nefsc_station_fall <- read_csv('./data/22560_UNION_FSCS_SVSTA_fall.csv')

nefsc_catch_fall <- read_csv('./data/22560_UNION_FSCS_SVCAT_fall.csv')
  
nefsc_fall <- left_join(nefsc_station_fall, nefsc_catch_fall, 
                           by = c("ID", "CRUISE6", "STRATUM", "TOW", "STATION"))




#joining the spring and fall survey datasets 
nefsc <- rbind(nefsc_spring, nefsc_fall)


rm(nefsc_station_spring)
rm(nefsc_catch_spring)
rm(nefsc_spring)
rm(nefsc_station_fall)
rm(nefsc_catch_fall)
rm(nefsc_fall)
```


## VW Trawl Data 
```{r}
#importing and joining the 2019 VW survey catch and station data and joining them 
vw_station_2019 <- read_csv('./data/VW_2019-2020_Tow_Info.csv')

vw_catch_2019 <- read_csv('./data/VW_2019-2020_WeightTable.csv')

vw_2019 <- left_join(vw_station_2019, vw_catch_2019, 
                           by = c("TowID"))


#importing and joining the 2020 VW survey catch and station data and joining them 
vw_station_2020 <- read_csv('./data/VW_2020-2021_TowInfo.csv')

vw_catch_2020 <- read_csv('./data/VW_2020-2021_WeightTable.csv')

vw_2020 <- left_join(vw_station_2020, vw_catch_2020, 
                           by = c("TowID"))


#joining the 2019 and 2020 survey datasets 
vw <- rbind(vw_2019, vw_2020)


#adding common species name column 
vw <- vw %>%
  mutate(common_name = case_when(
    SpeciesID == 10 ~ "Alewife", 
    SpeciesID == 124	~ "Monkfish",
    SpeciesID == 230	~ "Bluefish",
    SpeciesID == 511	~ "Butterfish",
    SpeciesID == 818	~ "Atlantic Cod",
    SpeciesID == 900	~ "Atlantic Croaker",
    SpeciesID == 930	~ "Cunner",
    SpeciesID == 960	~ "Cusk",
    SpeciesID == 1120	~ "Herring, Blueback",
    SpeciesID == 1150	~ "American Eel",
    SpeciesID == 1160  ~ "Eel, Conger",
    SpeciesID == 1200	~ "Flounder, Winter",
    SpeciesID == 1219	~ "Flounder, Summer (Fluke)",
    SpeciesID == 1220	~ "Flounder, Witch",
    SpeciesID == 1230	~ "Flounder, Yellowtail",
    SpeciesID == 1240	~ "Flounder, American Plaice",
    SpeciesID == 1250	~ "Flounder, Windowpane",
    SpeciesID == 1270	~ "Flounder, Fourspot",
    SpeciesID == 1290	~ "Flounder, Gulfstream",
    SpeciesID == 1300	~ "Flounder, Southern",
    SpeciesID == 1477	~ "Haddock",
    SpeciesID == 1520	~ "Hake, Red",
    SpeciesID == 1539	~ "Hake, White",
    SpeciesID == 1590	~ "Atlantic Halibut",
    SpeciesID == 1685	~ "Herring, Atlantic",
    SpeciesID == 2120	~ "Mackerel, Atlantic",
    SpeciesID == 2210	~ "Menhaden, Atlantic",
    SpeciesID == 2400	~ "Redfish",
    SpeciesID == 2500	~ "Ocean Pout",
    SpeciesID == 2695	~ "Pollock",
    SpeciesID == 3270	~ "Sea Raven",
    SpeciesID == 3295	~ "Scup",
    SpeciesID == 3350	~ "Black Sea bass",
    SpeciesID == 3400	~ "Sea Robin, Northern",
    SpeciesID == 3420	~ "Sea Robin, Striped",
    SpeciesID == 3446	~ "Weakfish",
    SpeciesID == 3474	~ "Shad, American",
    SpeciesID == 3511	~ "Dogfish, Smooth",
    SpeciesID == 3521	~ "Dogfish, Spiny",
    SpeciesID == 3531	~ "Shark, Thresher",
    SpeciesID == 3610	~ "Capelin",
    SpeciesID == 3650	~ "Skate, Mixed",
    SpeciesID == 3660	~ "Skate, Little",
    SpeciesID == 3670	~ "Skate, Winter",
    SpeciesID == 3680	~ "Skate, Barndoor",
    SpeciesID == 3690	~ "Skate, Smooth",
    SpeciesID == 3700	~ "Skate, Thorny",
    SpeciesID == 3720	~ "Skate, Clearnose",
    SpeciesID == 4180	~ "Striped Bass",
    SpeciesID == 4380	~ "Tautog",
    SpeciesID == 4811	~ "Shark, Porbeagle",
    SpeciesID == 4931	~ "Shark, Blue",
    SpeciesID == 5090	~ "Hake, Silver",
    SpeciesID == 5120	~ "Wolffish",
    SpeciesID == 6602	~ "Hake, Spotted",
    SpeciesID == 6616	~ "Kingfish, Northern",
    SpeciesID == 6640	~ "Cutlassfish, Atlantic",
    SpeciesID == 6678	~ "Sculpin, Longhorn",
    SpeciesID == 6790	~ "Wrymouth",
    SpeciesID == 6870	~ "Snail, Moonshell",
    SpeciesID == 7120	~ "Crab, Cancer",
    SpeciesID == 7270	~ "Lobster, American",
    SpeciesID == 7360	~ "Northern Shrimp",
    SpeciesID == 7690	~ "Clam, Surf",
    SpeciesID == 8009	~ "Sea Scallop",
    SpeciesID == 8010	~ "Squid, Atlantic Longfin",
    SpeciesID == 8020	~ "Squid, Shortfin")) %>%
  relocate(common_name, .after = SpeciesID)



rm(vw_station_2019)
rm(vw_catch_2019)
rm(vw_station_2020)
rm(vw_catch_2020)
rm(vw_2019)
rm(vw_2020)
```


# Filtering
## Filtering datasets for just trawl gears and after 2009
```{r}
#filtering the study fleet dataset to include only trawl gears and only after 2009
sf_trawl <- study_fleet %>%
  filter(VTR_GEAR_CODE %in% c('OHS', 'OTF', 'OTO', 'OTR')) %>%
      #OHS - otter trawl, haddock separator
      #OTF - otter trawl, bottom, fish 
      #OTM - otter trawl, midwater
      #OTO - otter trawl, bottom, other
      #OTR - otter trawl, ruhle 
      #OTS - otter trawl, bottom, shrimp
  filter(YEAR >= 2009) %>%
  mutate(survey_comercial_ID = 2)



#filter the observer data set to include only trawl gears and only after 2009
observer_trawl <- observer %>%
  filter(NEGEAR %in% c("050", "057", "150")) %>%
      #050 - Trawl, Otter, Bottom, Fish
      #057 - Trawl, Otter, Bottom, Haddock Separator
      #150 - Trawl, Otter, Bottom, Large Mesh Belly Panel
  mutate(trip_haul_ID = paste(TRIPID,HAULNUM, sep = '_')) %>%
  relocate(trip_haul_ID) %>%
  filter(YEARHBEG  >= 2009) %>%
  mutate(survey_comercial_ID = 3)

  
  
#filtering the nefsc survey dataset to only after 2009 because of the shift to the bigelow 
nefsc <- nefsc %>%
  mutate(cruise_station_ID = paste(CRUISE6,STATION, sep = '_')) %>%
  relocate(cruise_station_ID) %>%
  filter(EST_YEAR >= 2009) %>%
  mutate(BEGIN_EST_TOWDATE = as.POSIXct(BEGIN_EST_TOWDATE, format = "%m/%d/%y %H:%M")) %>%
  mutate(END_EST_TOWDATE = as.POSIXct(END_EST_TOWDATE, format = "%m/%d/%y %H:%M")) %>%
  mutate(BEGIN_GMT_TOWDATE = as.POSIXct(BEGIN_GMT_TOWDATE, format = "%m/%d/%y %H:%M")) %>%
  mutate(END_GMT_TOWDATE = as.POSIXct(END_GMT_TOWDATE, format = "%m/%d/%y %H:%M")) %>%
  mutate(survey_commerical_ID = 1)



#filtering the VW survey dataset - creating datetime columns and cleaning lat/long columns
vw <- vw %>%
  mutate(START_TOW_DATE = as.POSIXct(paste(TripDate, TowStartTime), format = "%m/%d/%y %H:%M", tz = "EST")) %>%
  mutate(END_TOW_DATE = as.POSIXct(paste(TripDate, TowEndTime), format = "%m/%d/%y %H:%M", tz = "EST")) %>%
  mutate(START_TOW_DATE_GMT = with_tz(START_TOW_DATE, "GMT")) %>%
  mutate(END_TOW_DATE_GMT = with_tz(END_TOW_DATE, "GMT")) %>%
  relocate(START_TOW_DATE, .after = TowStartTime) %>%
  relocate(START_TOW_DATE_GMT, .after = START_TOW_DATE) %>%
  relocate(END_TOW_DATE, .after = TowEndTime) %>%
  relocate(END_TOW_DATE_GMT, .after = END_TOW_DATE) %>%
  mutate_at(c("TowStartLat", "TowEndLat"), str_remove, "N ") %>%
  mutate_at(c("TowStartLong", "TowEndLong"), str_replace, "W ", "-") %>%
  mutate_at(c("TowStartLat", "TowEndLat", "TowStartLong", "TowEndLong"), str_replace, "(?<=\\.\\d\\d)\\.", "") %>%
  mutate(TotalWeight_lb = TotalWeight_kg*2.2046226218)





rm(study_fleet)
rm(observer)
```



## Slimming datasets
```{r}
#selecting just the variables of interest for study fleet dataset 
sf_trawl_slim <- sf_trawl %>%
  select(c("TRIP_ID", "VESSEL_NAME", "TARGET_SPECIES", "VTR_GEAR_CODE", 
           "EFFORT_ID", "COMMON_NAME", "NESPP4", "SPECIES_ITIS",
           "DISPOSITION_DESCR", "AREA_CODE", "SOAK_DUR_HRS", "EFFORT_NUM",
           "START_HAUL_DATE_GMT", "END_SET_DATE_GMT", "START_HAUL_LAT",
           "START_HAUL_LON", "END_SET_LAT", "END_SET_LON", "DEPTH_FTH", 
           "GEAR_QUANTITY", "GEAR_SIZE", "MESH_SIZE", "MESH_TYPE", 
           "HAIL_AMOUNT", "HAIL_AMOUNT_LB", "CALC_DUR_HR", "CALC_DIST_NM", 
           "MEAN_DPTH_M", "survey_comercial_ID")) %>%
  # select(-c("VES_NAME", "HULL_ID", "PPORT", "HPORT", "ACCSP_GEAR_CODE", 
  #           "PPST", "SAIL_PORT_NAME", "SAIL_STATE_POSTAL", "LAND_PORT_NAME", 
  #           "LAND_STATE_POSTAL", "START_SET_DATE_GMT", "START_SET_LAT", "START_SET_LON", 
  #           "END_HAUL_DATE_GMT")) %>%
  rename(START_TOW_DATE_GMT = START_HAUL_DATE_GMT) %>%
  rename(END_TOW_DATE_GMT = END_SET_DATE_GMT) %>%
  rename(START_TOW_LAT = START_HAUL_LAT) %>% 
  rename(START_TOW_LON = START_HAUL_LON) %>%
  rename(END_TOW_LAT = END_SET_LAT) %>%
  rename(END_TOW_LON = END_SET_LON) %>%
  drop_na(END_TOW_LAT) %>%
  drop_na(END_TOW_LON)
  


#selecting just the variables of interest for observer dataset 
ob_trawl_slim <- observer_trawl %>%
  mutate(START_TOW_DATE = make_date(YEARHBEG, MONTHHBEG, DAYHBEG)) %>%
  select(c("trip_haul_ID", "START_TOW_DATE", "AREA", "NEGEAR", "GEARNM", "NETNAME", "NETTYPE", 
         "GRCABTYP", "BRDLGTYP", "BRDLGTYP", "FTROPTYP", "CODLINERUSD", "NESPP4", 
         "COMNAME", "CATDISP", "FISHDISP", "FISHDISPDESC", "GIS_LATHBEG", 
         "GIS_LONHBEG", "GIS_LATHEND", "GIS_LONHEND", "HAULDUR", "HAILWT", 
         "LIVE_WT", "survey_comercial_ID")) %>%
  # rename(END_TOW_DATE_GMT = END_SET_DATE_GMT) %>%
    #no end date information in the observer dataset 
  rename(START_TOW_LAT = GIS_LATHBEG) %>% 
  rename(START_TOW_LON = GIS_LONHBEG) %>%
  rename(END_TOW_LAT = GIS_LATHEND) %>%
  rename(END_TOW_LON = GIS_LONHEND) %>%
  drop_na(END_TOW_LAT) %>%
  drop_na(END_TOW_LON)


#selecting just the variables of interest for the nefsc dataset 
nefsc_slim <- nefsc %>%
  select(c("cruise_station_ID", "STRATUM", "AREA", "SVVESSEL", "SVGEAR", 
           "BEGIN_GMT_TOWDATE", "END_GMT_TOWDATE", "DECDEG_BEGLAT", 
           "DECDEG_BEGLON", "DECDEG_ENDLAT", "DECDEG_ENDLON", 
           "TOWDUR", "AVGDEPTH", "LOGGED_SPECIES_NAME", "SVSPP", 
           "EXPCATCHNUM", "EXPCATCHWT")) %>%
  # select(-c("EST_MONTH","EST_DAY", "EST_JULIAN_DAY", "BEGLAT", "BEGLON", "ENDLAT", 
  #           "ENDLON", "COURSE", "RPM", "DOPDISTW", "...11", "...12", 
  #           "BEGIN_EST_TOWDATE", "END_EST_TOWDATE", "SURFSALIN", "SURFTEMP", 
  #           "XBT", "BKTTEMP", "SWELLHGT", "SWELLDIR", "WAVEHGT", "WEATHER", 
  #           "WINDSP", "WINDDIR", "BAROPRESS", "CLOUD", "AIRTEMP", "DESSPEED", "DOPDISTB", 
  #           "HEADING", "PITCH")) %>%
  rename(START_TOW_DATE_GMT = BEGIN_GMT_TOWDATE) %>%
  rename(END_TOW_DATE_GMT = END_GMT_TOWDATE) %>%
  rename(START_TOW_LAT = DECDEG_BEGLAT) %>%
  rename(START_TOW_LON = DECDEG_BEGLON) %>%
  rename(END_TOW_LAT = DECDEG_ENDLAT) %>%
  rename(END_TOW_LON = DECDEG_ENDLON) %>%
  drop_na(END_TOW_LAT) %>%
  drop_na(END_TOW_LON)
  


#selecting just the variables of interest for the VW dataset 
vw_slim <- vw %>% 
  select("TowID", "VesselID", "GearID", "START_TOW_DATE_GMT", "TowStartLat", 
         "TowStartLong", "TowStartDepth", "END_TOW_DATE_GMT", "TowEndLat", 
         "TowEndLong", "TowEndLong", "TowEndDepth", "SpeciesID", 
         "common_name", "TotalWeight_lb") %>%
  rename(START_TOW_LAT = TowStartLat) %>%
  rename(START_TOW_LON = TowStartLong) %>%
  rename(END_TOW_LAT = TowEndLat) %>%
  rename(END_TOW_LON = TowEndLong) %>%
  mutate(across(c("START_TOW_LAT", "START_TOW_LON", "END_TOW_LAT", "END_TOW_LON"), as.double))
  

  

#creating a dataset for just the station inf
# nefsc_station <- rbind(nefsc_station_fall, nefsc_station_spring)
# nefsc_station <- nefsc_station %>%
#   mutate(cruise_station_ID = paste(CRUISE6,STATION, sep = '_')) %>%
#   relocate(cruise_station_ID) %>%
#   filter(EST_YEAR >= 2009) %>%
#   mutate(BEGIN_EST_TOWDATE = as.POSIXct(BEGIN_EST_TOWDATE, format = "%m/%d/%y %H:%M")) %>%
#   mutate(END_EST_TOWDATE = as.POSIXct(END_EST_TOWDATE, format = "%m/%d/%y %H:%M")) %>%
#   mutate(BEGIN_GMT_TOWDATE = as.POSIXct(BEGIN_GMT_TOWDATE, format = "%m/%d/%y %H:%M")) %>%
#   mutate(END_GMT_TOWDATE = as.POSIXct(END_GMT_TOWDATE, format = "%m/%d/%y %H:%M")) %>%
#   mutate(survey_commerical_ID = 1) %>%
# 
#   select(c("cruise_station_ID", "STRATUM", "AREA", "SVGEAR", 
#            "BEGIN_GMT_TOWDATE", "END_GMT_TOWDATE", "DECDEG_BEGLAT", 
#            "DECDEG_BEGLON", "DECDEG_ENDLAT", "DECDEG_ENDLON", 
#            "TOWDUR", "AVGDEPTH")) %>%
#   rename(START_TOW_DATE_GMT = BEGIN_GMT_TOWDATE) %>%
#   rename(END_TOW_DATE_GMT = END_GMT_TOWDATE) %>%
#   rename(START_TOW_LAT = DECDEG_BEGLAT) %>%
#   rename(START_TOW_LON = DECDEG_BEGLON) %>%
#   rename(END_TOW_LAT = DECDEG_ENDLAT) %>%
#   rename(END_TOW_LON = DECDEG_ENDLON) %>%
#   drop_na(END_TOW_LAT) %>%
#   drop_na(END_TOW_LON)

rm(sf_trawl)
rm(observer_trawl)
rm(nefsc)
rm(vw)
```


## Assigning NEFSC Survey Strata to Commercial/VW Tows 
```{r}
#Assigning NEFSC survey strata to commercial Study Fleet tows 
#read in the nefsc survey strata data
sf::sf_use_s2(FALSE)
nefsc_strata <- st_read(dsn = "./data/strata") %>%
  st_set_crs(4269)

st_make_valid(nefsc_strata)

#creating a midpoint variable of the tow and using that as the determining criteria
sf_trawl_slim <- sf_trawl_slim %>%
  drop_na(c(START_TOW_LAT, END_TOW_LAT, START_TOW_LON, END_TOW_LON)) %>%
  mutate(midpoint_lat = rowMeans(across(c(START_TOW_LAT, END_TOW_LAT)))) %>%
  mutate(midpoint_long = rowMeans(across(c(START_TOW_LON, END_TOW_LON))))

#selecting just the midpoint values because the geometry field will not be created correctly with all the other variables in the dataset
sf_points <- sf_trawl_slim %>%  
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  select(midpoint_lat, midpoint_long)

#turning the lat/long variables into an sf feature 
sf_points_sf <- st_as_sf(sf_points, coords = c("midpoint_long", "midpoint_lat"), 
                             crs = st_crs(nefsc_strata))

#running the actual intersection of the tows in the strata and creating a column in the points dataset specifying which stratum the tows occured in 
sf_points$strata <- apply(st_intersects(nefsc_strata, sf_points_sf, sparse = FALSE), 2, 
               function(col) { 
                  nefsc_strata[which(col), ]$STRATA
               })

#changing the strata column to numeric instead of a list 
sf_points <- sf_points %>%
  mutate(strata = as.numeric(strata))

#left joining the points dataset (with the stratum column) to the OG study fleet trawl dataset by the lat/long columns
sf_trawl_slim <- left_join(sf_trawl_slim, sf_points, by = c("midpoint_lat", "midpoint_long"))





#Assigning NEFSC survey strata to commercial Observer tows 
#creating a midpoint variable of the tow and using that as the determining criteria
ob_trawl_slim <- ob_trawl_slim %>%
  drop_na(c(START_TOW_LAT, END_TOW_LAT, START_TOW_LON, END_TOW_LON)) %>%
  mutate(midpoint_lat = rowMeans(across(c(START_TOW_LAT, END_TOW_LAT)))) %>%
  mutate(midpoint_long = rowMeans(across(c(START_TOW_LON, END_TOW_LON))))

#selecting just the midpoint values because the geometry field will not be created correctly with all the other variables in the dataset
ob_points <- ob_trawl_slim %>%  
  distinct(trip_haul_ID, .keep_all = TRUE) %>%
  select(midpoint_lat, midpoint_long)

#turning the lat/long variables into an sf feature 
ob_points_sf <- st_as_sf(ob_points, coords = c("midpoint_long", "midpoint_lat"), 
                             crs = st_crs(nefsc_strata))

#running the actual intersection of the tows in the strata and creating a column in the points dataset specifying which stratum the tows occured in 
ob_points$strata <- apply(st_intersects(nefsc_strata, ob_points_sf, sparse = FALSE), 2, 
               function(col) { 
                  nefsc_strata[which(col), ]$STRATA
               })

#changing the strata column to numeric instead of a list 
ob_points <- ob_points %>%
  mutate(strata = as.numeric(strata))

#left joining the points dataset (with the stratum column) to the OG study fleet trawl dataset by the lat/long columns
ob_trawl_slim <- left_join(ob_trawl_slim, ob_points, by = c("midpoint_lat", "midpoint_long"))




rm(sf_points)
rm(sf_points_sf)
rm(ob_points)
rm(ob_points_sf)
```



# Renaming Variables of Interest (so they are consistent across datasets)
```{r}

```



# Saving the Slimmed Down Datasets 
```{r}
# write.csv(sf_trawl_slim, './data/sf_trawl_slim.csv', row.names = FALSE)
# write.csv(ob_trawl_slim, './data/ob_trawl_slim.csv', row.names = FALSE)
# write.csv(nefsc_slim, './data/nefsc_slim.csv', row.names = FALSE)
# write.csv(vw_slim, './data/vw_slim.csv', row.names = FALSE)
```



