---
title: "matched_tow_analysis"
output: html_document
date: '2022-03-28'
---

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(skimr)
library(data.table)
library(fuzzyjoin)
library(lubridate)
library(kableExtra)

library(maps) # land masses
library(rgdal) # read OGR vector maps into Spatial objects
library(viridis) # for customizing scale bars
library(mapproj)
library(hexbin)
library(sf)
library(scales)
library(beepr)
```



# Matchcing Tows

## SF w NEFSC fuzzy join based on prosopsed criteria 
```{r}
rm(sf_trawl)
rm(nefsc)

memory.limit(size = 999999)

#Fuzzy joining sf tows that are within 1mi and 1 day of nefsc tows
paired_tows_1mi_24hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -24 & time_dif < 24)


#confirming that I have 6 matches 
paired_tows_1mi_24hr %>%
  count(cruise_station_ID)
paired_tows_1mi_24hr %>%
  count(EFFORT_ID)

view(paired_tows_1mi_24hr)



#Fuzzy joining sf tows that are within 5mi and 3 day of nefsc tows
paired_tows_5mi_72hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 5, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -72 & time_dif < 72)


paired_tows_5mi_72hr %>%
  count(cruise_station_ID)
paired_tows_5mi_72hr %>%
  count(EFFORT_ID)




#Fuzzy joining sf tows that are within 10mi and 5 day of nefsc tows
#this one doesn't run because I don't have enough computing power

# paired_tows_10mi_120hr <- nefsc_slim %>% 
#   fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
#                                                    "END_TOW_LON"),
#                            max_dist = 10, unit = "miles") %>%
#   mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
#   filter(time_dif > -120 & time_dif < 120)
# 
# 
# paired_tows_10mi_120hr %>%
#   count(cruise_station_ID)
# paired_tows_10mi_120hr %>%
#   count(EFFORT_ID)


```





## SF w NEFSC fuzzy join for all combinations of miles/days 
```{r}
####### Run the Fuzzy Join for all combinations of miles/days from 1-8 #########

#Fuzzy joining sf tows that are within 1mi and 1days of nefsc tows
paired_tows_1mi_24hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -24 & time_dif < 24)

paired_tows_1mi_24hr %>%
  count(cruise_station_ID)
paired_tows_1mi_24hr %>%
  count(EFFORT_ID)



#Fuzzy joining sf tows that are within 1mi and 2days of nefsc tows
paired_tows_1mi_48hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -48 & time_dif < 48)

paired_tows_1mi_48hr %>%
  count(cruise_station_ID)
paired_tows_1mi_48hr %>%
  count(EFFORT_ID)



#Fuzzy joining sf tows that are within 1mi and 3days of nefsc tows
paired_tows_1mi_72hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -72 & time_dif < 72)

paired_tows_1mi_72hr %>%
  count(cruise_station_ID)
paired_tows_1mi_72hr %>%
  count(EFFORT_ID)


#Fuzzy joining sf tows that are within 1mi and 4days of nefsc tows
paired_tows_1mi_96hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -96 & time_dif < 96)

paired_tows_1mi_96hr %>%
  count(cruise_station_ID)
paired_tows_1mi_96hr %>%
  count(EFFORT_ID)




#Fuzzy joining sf tows that are within 1mi and 5days of nefsc tows
paired_tows_1mi_120hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -120 & time_dif < 120)

paired_tows_1mi_120hr %>%
  count(cruise_station_ID)
paired_tows_1mi_120hr %>%
  count(EFFORT_ID)



#Fuzzy joining sf tows that are within 1mi and 6days of nefsc tows
paired_tows_1mi_144hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -144 & time_dif < 144)

paired_tows_1mi_144hr %>%
  count(cruise_station_ID)
paired_tows_1mi_144hr %>%
  count(EFFORT_ID) 


#Fuzzy joining sf tows that are within 1mi and 7days of nefsc tows
paired_tows_1mi_168hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -168 & time_dif < 168)

paired_tows_1mi_168hr %>%
  count(cruise_station_ID)
paired_tows_1mi_168hr %>%
  count(EFFORT_ID) 



#Fuzzy joining sf tows that are within 1mi and 8days of nefsc tows
paired_tows_1mi_192hr <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(sf_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(END_TOW_DATE_GMT.x, END_TOW_DATE_GMT.y, units = "hours")) %>%
  filter(time_dif > -192 & time_dif < 192)

paired_tows_1mi_192hr %>%
  count(cruise_station_ID)
paired_tows_1mi_192hr %>%
  count(EFFORT_ID)

```



## Observer w NEFSC fuzzy join datasets based on proposed criteria 
```{r}
paired_tows_1mi_24hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -1 & time_dif < 1)


paired_tows_1mi_24hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_24hr_ob %>%
  count(trip_haul_ID)
```




## Observer w NEFSC fuzzy join for all combinations of miles/days 
```{r}
####### Run the Fuzzy Join for all combinations of miles/days from 1-8 #########

#Fuzzy joining sf tows that are within 1mi and 1days of nefsc tows
paired_tows_1mi_24hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -1 & time_dif < 1)

paired_tows_1mi_24hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_24hr_ob %>%
  count(trip_haul_ID)



#Fuzzy joining sf tows that are within 1mi and 2days of nefsc tows
paired_tows_1mi_48hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -2 & time_dif < 2)

paired_tows_1mi_48hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_48hr_ob %>%
  count(trip_haul_ID)



#Fuzzy joining sf tows that are within 1mi and 3days of nefsc tows
paired_tows_1mi_72hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -3 & time_dif < 3)

paired_tows_1mi_72hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_72hr_ob %>%
  count(trip_haul_ID)


#Fuzzy joining sf tows that are within 1mi and 4days of nefsc tows
paired_tows_1mi_96hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -4 & time_dif < 4)

paired_tows_1mi_96hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_96hr_ob %>%
  count(trip_haul_ID)




#Fuzzy joining sf tows that are within 1mi and 5days of nefsc tows
paired_tows_1mi_120hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -5 & time_dif < 5)

paired_tows_1mi_120hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_120hr_ob %>%
  count(trip_haul_ID)



#Fuzzy joining sf tows that are within 1mi and 6days of nefsc tows
paired_tows_1mi_144hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -6 & time_dif < 6)

paired_tows_1mi_144hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_144hr_ob %>%
  count(trip_haul_ID) 


#Fuzzy joining sf tows that are within 1mi and 7days of nefsc tows
paired_tows_1mi_168hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -7 & time_dif < 7)

paired_tows_1mi_168hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_168hr_ob %>%
  count(trip_haul_ID) 



#Fuzzy joining sf tows that are within 1mi and 8days of nefsc tows
paired_tows_1mi_192hr_ob <- nefsc_slim %>% 
  fuzzyjoin::geo_inner_join(ob_trawl_slim, by = c("END_TOW_LAT", 
                                                   "END_TOW_LON"),
                           max_dist = 1, unit = "miles") %>%
  mutate(time_dif = difftime(START_TOW_DATE_GMT, START_TOW_DATE, units = "days")) %>%
  filter(time_dif > -8 & time_dif < 8)

paired_tows_1mi_192hr_ob %>%
  count(cruise_station_ID)
paired_tows_1mi_192hr_ob %>%
  count(trip_haul_ID)

```




