---
title: "re_analysis_tighter_matches"
output: html_document
date: "2023-01-30"
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(janitor)
library(skimr)
library(data.table)
library(fuzzyjoin)
library(lubridate)
library(kableExtra)
library(modEvA)

library(maps) # land masses
library(rgdal) # read OGR vector maps into Spatial objects
library(viridis) # for customizing scale bars
library(mapproj)
library(hexbin)
library(sf)
library(scales)
library(gridExtra)
library(openxlsx)
library(beepr)
library(purrr)
library(broom)
library(aod)
library(car)
library(effects)

```

# Read-In the Data
```{r}
#study fleet
paired_tows_2mi_48hr <- read.csv('./data/paired_tows_2mi_48hr.csv')
paired_tows_3mi_72hr <- read.csv('./data/paired_tows_3mi_72hr.csv')

#observer
paired_tows_2mi_48hr_ob <- read.csv('./data/paired_tows_2mi_48hr_ob.csv')
# paired_tows_3mi_72hr_ob <- read.csv('./data/paired_tows_3mi_72hr_ob.csv')
```


# Data for Maps 
```{r, message = FALSE, warning = FALSE}
#Additional Data for Maps
#Statistical Areas
sareas <- st_read(dsn = "./data/Statistical_Areas_2010_withNames") %>%
  st_set_crs(4269)
sareas <- sareas %>% filter(Id %in% c("464", "465", "511", "512", "513", "514", "515", "521", "522", "525", "526", "537", "538", "539", "551", "561", "562", "611", "612", "613", "543", "542", "541", "534", "533", "616", "615", "614", "621", "622", "623", "624"))  
centroids <- sf::st_coordinates(st_centroid(sareas)) 
areas <- cbind(sareas, centroids)


#Land Mass
states <- map_data("state")
NEUS <- subset(states, region %in% c("Maine", "massachusetts", "new hampshire", "vermont", "maine", "rhode island",
                "connecticut","new york","new jersey","delaware","pennsylvania",
                            "maryland","virginia","north carolina","west virginia"))


#NEFSC Survey Strata
sf::sf_use_s2(FALSE)
nefsc_strata <- st_read(dsn = "./data/strata") %>%
  st_set_crs(4269)


```


# Function Creation 
```{r}
# Function Creation 
##############################################################################
#################### FUNCTIONS FOR T-TESTS ###################################
##############################################################################
box.plot_diff <- function(x) {
  x %>% 
  ggplot() + 
  geom_boxplot(aes(y = diff)) + 
  labs(y = bquote("Difference between Study Fleet and NEFSC CPUA [lb/"*km^2*"]")) + 
  theme_classic()
}
box.plot_diff_log <- function(x) {
  x %>% 
  ggplot() + 
  geom_boxplot(aes(y = diff_of_logs)) + 
  labs(y = bquote("Ln(Difference between Study Fleet and NEFSC CPUA [lb/"*km^2*"])")) + 
  theme_classic()
}
hist_kh_diff <- function(x) {
  x %>%  
  ggplot() + 
  geom_histogram(aes(x = diff)) + 
  labs(x = bquote("Difference between Study Fleet and NEFSC CPUA [lb/"*km^2*"]"), 
       y = "Count") + 
  theme_classic()
}
hist_kh_diff_log <- function(x) {
  x %>%  
  ggplot() + 
  geom_histogram(aes(x = diff_of_logs)) + 
  labs(x = bquote("Ln(Difference between Study Fleet and NEFSC CPUA [lb/"*km^2*"])"), 
       y = "Count") + 
  theme_classic()
}
####################### STUFF I DIDNT END UP USING ############################
CPUA_label <- bquote("CPUA [lb/"*km^2*"]")
logCPUA_lable <- bquote("Log(CPUA [lb/"*km^2*"])")
#plots to check for normality before t-tests 
#boxplot of catch per unit area
box.plot <- function(x) {
  x %>%
  pivot_longer(cols = c(sf_species_cpua, nefsc_species_cpua),
               names_to = "Trawl",
               values_to = "CPUA") %>%
  filter(CPUA < 10000) %>%
  ggplot() +
  geom_boxplot(aes(x = Trawl, y = CPUA)) +
  labs(x = "Trawl Type", y = CPUA_label) +
  scale_x_discrete(labels = c("nefsc_species_cpua" = "NEFSC",
                              "sf_species_cpua" = "Study Fleet")) +
  theme_classic()
}
#histogram of catch per unit area
hist_kh <- function(x) {
  x %>%
  ggplot() +
  geom_histogram(aes(x = sf_species_cpua, y = ..density.., fill = "Study Fleet")) +
  # geom_label(aes(x = Inf, y = Inf, label = "Study Fleet CPUE", vjust =1 , hjust = 1), color = "red") +
  geom_histogram(aes(x = nefsc_species_cpua, y = -..density.., fill = "NEFSC")) +
  # geom_label(aes(x = Inf, y = -Inf, label = "NEFSC CPUE", vjust = -1, hjust = 1), color = "blue") +
  labs(x = CPUA_label, y = "Density",
       # title = "Histogram of CPUE for x",
       # subtitle = "Pairs within 5 mi and 72 hrs"
       ) +
  xlim(0,2000) +
  scale_fill_manual(name = "Dataset",
                    values = c("Study Fleet" = "red", "NEFSC" = "blue"),
                    labels = c("Study Fleet", "NEFSC")) +
  theme_classic()
}
#   
# 
# #boxplot with log-transformed data 
# box.log.plot <- function(x) {
#   x %>% 
#   pivot_longer(cols = c(log_sf_species_cpua, log_nefsc_species_cpua), 
#                names_to = "Trawl", 
#                values_to = "CPUA") %>%
#   filter(CPUA < 10000) %>%
#   ggplot() + 
#   geom_boxplot(aes(x = Trawl, y = CPUA)) + 
#   labs(x = "Trawl Type", y = logCPUA_lable) + 
#   scale_x_discrete(labels = c("log_nefsc_species_cpua" = "NEFSC", 
#                               "log_sf_species_cpua" = "Study Fleet")) + 
#   theme_classic()
# }
# 
# #histogram with log-transformed data 
# hist_log_kh <- function(x) {
#   x %>%  
#   ggplot() + 
#   geom_histogram(aes(x = log_sf_species_cpua, y = ..density.., fill = "Study Fleet")) + 
#   # geom_label(aes(x = Inf, y = Inf, label = "Study Fleet CPUE", vjust =1 , hjust = 1), color = "red") +
#   geom_histogram(aes(x = log_nefsc_species_cpua, y = -..density.., fill = "NEFSC")) + 
#   # geom_label(aes(x = Inf, y = -Inf, label = "NEFSC CPUE", vjust = -1, hjust = 1), color = "blue") +
#   labs(x = logCPUA_lable, y = "Density", 
#        # title = "Histogram of CPUE for x", 
#        # subtitle = "Pairs within 5 mi and 72 hrs"
#        ) + 
#   scale_fill_manual(name = "Dataset", 
#                     values = c("Study Fleet" = "red", "NEFSC" = "blue"), 
#                     labels = c("Study Fleet", "NEFSC")) + 
#   theme_classic()
# }
# 
# 
# ############## FUNCTIONS FOR T-TESTS FOR OBSERVER DATA #######################
# 
# #plots to check for normality before t-tests 
# #boxplot of catch per unit area
box.plot_ob <- function(x) {
  x %>%
  pivot_longer(cols = c(ob_species_cpua, nefsc_species_cpua),
               names_to = "Trawl",
               values_to = "CPUA") %>%
  filter(CPUA < 10000) %>%
  ggplot() +
  geom_boxplot(aes(x = Trawl, y = CPUA)) +
  labs(x = "Trawl Type", y = CPUA_label) +
  scale_x_discrete(labels = c("nefsc_species_cpua" = "NEFSC",
                              "ob_species_cpua" = "Observer")) +
  theme_classic()
}
#histogram of catch per unit area
hist_kh_ob <- function(x) {
  x %>%
  ggplot() +
  geom_histogram(aes(x = ob_species_cpua, y = ..density.., fill = "Observer")) +
  # geom_label(aes(x = Inf, y = Inf, label = "Observer CPUE", vjust =1 , hjust = 1), color = "red") +
  geom_histogram(aes(x = nefsc_species_cpua, y = -..density.., fill = "NEFSC")) +
  # geom_label(aes(x = Inf, y = -Inf, label = "NEFSC CPUE", vjust = -1, hjust = 1), color = "blue") +
  labs(x = CPUA_label, y = "Density",
       # title = "Histogram of CPUE for x",
       # subtitle = "Pairs within 5 mi and 72 hrs"
       ) +
  xlim(0,2000) +
  scale_fill_manual(name = "Dataset",
                    values = c("Observer" = "red", "NEFSC" = "blue"),
                    labels = c("Observer", "NEFSC")) +
  theme_classic()
}
#   
# 
# #boxplot with log-transformed data 
# box.log.plot_ob <- function(x) {
#   x %>% 
#   pivot_longer(cols = c(log_ob_species_cpua, log_nefsc_species_cpua), 
#                names_to = "Trawl", 
#                values_to = "CPUA") %>%
#   filter(CPUA < 10000) %>%
#   ggplot() + 
#   geom_boxplot(aes(x = Trawl, y = CPUA)) + 
#   labs(x = "Trawl Type", y = logCPUA_lable) + 
#   scale_x_discrete(labels = c("log_nefsc_species_cpua" = "NEFSC", 
#                               "log_ob_species_cpua" = "Observer")) + 
#   theme_classic()
# }
# 
# #histogram with log-transformed data 
# hist_log_kh_ob <- function(x) {
#   x %>%  
#   ggplot() + 
#   geom_histogram(aes(x = log_ob_species_cpua, y = ..density.., fill = "Observer")) + 
#   # geom_label(aes(x = Inf, y = Inf, label = "Study Fleet CPUE", vjust =1 , hjust = 1), color = "red") +
#   geom_histogram(aes(x = log_nefsc_species_cpua, y = -..density.., fill = "NEFSC")) + 
#   # geom_label(aes(x = Inf, y = -Inf, label = "NEFSC CPUE", vjust = -1, hjust = 1), color = "blue") +
#   labs(x = logCPUA_lable, y = "Density", 
#        # title = "Histogram of CPUE for x", 
#        # subtitle = "Pairs within 5 mi and 72 hrs"
#        ) + 
#   scale_fill_manual(name = "Dataset", 
#                     values = c("Observer" = "red", "NEFSC" = "blue"), 
#                     labels = c("Observer", "NEFSC")) + 
#   theme_classic()
# }
##############################################################################
######################## FUNCTIONS FOR MODELLING #############################
##############################################################################
#trying to  create functions because I will be running the same models for every species dataset 
covars <- c("season", "mgmt_area", "AVGDEPTH", "BOTTEMP")
combos <- purrr::map(1:4, ~as.data.frame(t(combn(covars, .x))))
formulae <- combos %>%
  map_dfr(unite, col="formula", sep = " + ") %>%
  mutate(formula = paste0("relative_efficiency ~  VESSEL_NAME +", formula))
#fit models (takes dataset)
fit.models <- function(x) {
  formulae$formula %>% purrr::map( ~glm(.x, family = binomial, data=x))
}
#compare models (takes list of models created by fit.models())
compare.models <- function(x) {
  formulae %>%
  mutate(aic =  purrr::map_dbl(x, AIC)) %>%
  arrange(desc(aic)) %>%
  mutate(deltaAIC = aic - aic[15]) %>%
  mutate(rsq =  purrr::map_dbl(x, Dsquared)) %>% 
  mutate(rsq = sprintf("%0.2f", rsq)) %>%
  mutate(aic = sprintf("%1.0f", aic)) %>%
  mutate(deltaAIC = sprintf("%1.0f", deltaAIC)) %>%
  kbl(col.names = (c("Model", "AIC", "deltaAIC","Deviance Explained"))) %>%
  kable_classic("striped", full_width = FALSE)
}
############## FUNCTIONS FOR MODELING OBSERVER DATA ###########################
#trying to  create functions because I will be running the same models for every species dataset 
covars <- c("season", "mgmt_area", "AVGDEPTH", "BOTTEMP")
combos <- purrr::map(1:4, ~as.data.frame(t(combn(covars, .x))))
formulae_ob <- combos %>%
  map_dfr(unite, col="formula", sep = " + ") %>%
  mutate(formula = paste0("relative_efficiency ~  trawl_type +", formula))
#fit models (takes dataset)
fit.models_ob <- function(x) {
  formulae_ob$formula %>% purrr::map( ~glm(.x, family = binomial, data=x))
}
#compare models (takes list of models created by fit.models())
compare.models_ob <- function(x) {
  formulae_ob %>%
  mutate(aic =  purrr::map_dbl(x, AIC)) %>%
  arrange(desc(aic)) %>%
  mutate(deltaAIC = aic - aic[15]) %>%
  mutate(rsq =  purrr::map_dbl(x, Dsquared)) %>% 
  mutate(rsq = sprintf("%0.2f", rsq)) %>%
  mutate(aic = sprintf("%1.0f", aic)) %>%
  mutate(deltaAIC = sprintf("%1.0f", deltaAIC)) %>%
  kbl(col.names = (c("Model", "AIC", "deltaAIC","Deviance Explained"))) %>%
  kable_classic("striped", full_width = FALSE)
}
```




# Datasets 
```{r}
#study fleet
#2mi and 48 hrs
paired_tows_2mi_48hr_re <- paired_tows_2mi_48hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712 | #cod 
         SVSPP == 74 & SPECIES_ITIS == 164744 | #haddock
         SVSPP == 75 & SPECIES_ITIS == 164727 | #pollock
         SVSPP == 105 & SPECIES_ITIS == 172909 | #yellowtail flounder
         SVSPP == 102 & SPECIES_ITIS == 172877 | #american plaice
         SVSPP == 107 & SPECIES_ITIS == 172873 | #witch flounder
         SVSPP == 76 & SPECIES_ITIS == 164732  | #white hake
         SVSPP == 108 & SPECIES_ITIS == 172746 | #windowpane
         SVSPP == 106 & SPECIES_ITIS == 172905 | #winter flounder
         SVSPP == 155 & SPECIES_ITIS == 166774 | #acadian redfish
         SVSPP == 101 & SPECIES_ITIS == 172933 | #atlantic halibut   #NE Groundfish spp

    
         SVSPP == 72 & SPECIES_ITIS == 164791 | #silver hake
         SVSPP == 77 & SPECIES_ITIS == 164730 | #red hake
         SVSPP == 78 & SPECIES_ITIS == 164731 | #spotted hake
           
         SVSPP == 103 & SPECIES_ITIS == 172735 | #summer flounder
         SVSPP == 104 & SPECIES_ITIS == 172739 | #fourspot flounder
    
         SVSPP == 197 & SPECIES_ITIS == 164499 | #goosefish
         SVSPP == 15 & SPECIES_ITIS == 160617    #spiny dogfish
        ) %>%
  drop_na(sf_species_cpua, nefsc_species_cpua) %>%
  filter(CATCHWT_updated > 0) %>%
  filter(sf_species_cpua > 0) %>%
  mutate(old_relative_efficiency = log(sf_species_cpua)/log(nefsc_species_cpua)) %>%
  mutate(relative_efficiency = nefsc_species_cpua/(nefsc_species_cpua + sf_species_cpua)) %>%
  mutate(mgmt_area = case_when(
    AREA_CODE %in% c(511, 512, 513, 514, 515) ~ "GOM", 
    AREA_CODE %in% c(521, 522, 526, 525, 561, 562, 551, 552) ~ "GB", 
    AREA_CODE %in% c(611, 612, 613, 539, 538, 537) ~ "SNE"
  )) %>%
  mutate(season = case_when(
    month(START_TOW_DATE_GMT.x) %in% c(03, 04, 05) ~ "Spring", 
    month(START_TOW_DATE_GMT.x) %in% c(09, 10, 11) ~ "Fall", 
  )) %>%
  mutate(dayNight = case_when(
    dayNight_sf == "day" & dayNight_nefsc == "day" ~ "day", 
    dayNight_sf == "night" & dayNight_nefsc == "night" ~ "night", 
    dayNight_sf == "day" & dayNight_nefsc == "night" ~ "mismatch",
    dayNight_sf == "night" & dayNight_nefsc == "day" ~ "mismatch", 
  )) %>%
  mutate(towTime = case_when(
    time_dif > 0 ~ "nefsc_first", 
    time_dif < 0 ~ "sf_first"
  )) %>%
  drop_na(AVGDEPTH, BOTTEMP, dayNight, towTime, mgmt_area) %>%
  distinct() 



#3mi and 72 hrs
paired_tows_3mi_72hr_re <- paired_tows_3mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712 | #cod 
         SVSPP == 74 & SPECIES_ITIS == 164744 | #haddock
         SVSPP == 75 & SPECIES_ITIS == 164727 | #pollock
         SVSPP == 105 & SPECIES_ITIS == 172909 | #yellowtail flounder
         SVSPP == 102 & SPECIES_ITIS == 172877 | #american plaice
         SVSPP == 107 & SPECIES_ITIS == 172873 | #witch flounder
         SVSPP == 76 & SPECIES_ITIS == 164732  | #white hake
         SVSPP == 108 & SPECIES_ITIS == 172746 | #windowpane
         SVSPP == 106 & SPECIES_ITIS == 172905 | #winter flounder
         SVSPP == 155 & SPECIES_ITIS == 166774 | #acadian redfish
         SVSPP == 101 & SPECIES_ITIS == 172933 | #atlantic halibut   #NE Groundfish spp

    
         SVSPP == 72 & SPECIES_ITIS == 164791 | #silver hake
         SVSPP == 77 & SPECIES_ITIS == 164730 | #red hake
         SVSPP == 78 & SPECIES_ITIS == 164731 | #spotted hake
           
         SVSPP == 103 & SPECIES_ITIS == 172735 | #summer flounder
         SVSPP == 104 & SPECIES_ITIS == 172739 | #fourspot flounder
    
         SVSPP == 197 & SPECIES_ITIS == 164499 | #goosefish
         SVSPP == 15 & SPECIES_ITIS == 160617    #spiny dogfish
        ) %>%
  drop_na(sf_species_cpua, nefsc_species_cpua) %>%
  filter(CATCHWT_updated > 0) %>%
  filter(sf_species_cpua > 0) %>%
  mutate(old_relative_efficiency = log(sf_species_cpua)/log(nefsc_species_cpua)) %>%
  mutate(relative_efficiency = nefsc_species_cpua/(nefsc_species_cpua + sf_species_cpua)) %>%
  mutate(mgmt_area = case_when(
    AREA_CODE %in% c(511, 512, 513, 514, 515) ~ "GOM", 
    AREA_CODE %in% c(521, 522, 526, 525, 561, 562, 551, 552) ~ "GB", 
    AREA_CODE %in% c(611, 612, 613, 539, 538, 537) ~ "SNE"
  )) %>%
  mutate(season = case_when(
    month(START_TOW_DATE_GMT.x) %in% c(03, 04, 05) ~ "Spring", 
    month(START_TOW_DATE_GMT.x) %in% c(09, 10, 11) ~ "Fall", 
  )) %>%
  mutate(dayNight = case_when(
    dayNight_sf == "day" & dayNight_nefsc == "day" ~ "day", 
    dayNight_sf == "night" & dayNight_nefsc == "night" ~ "night", 
    dayNight_sf == "day" & dayNight_nefsc == "night" ~ "mismatch",
    dayNight_sf == "night" & dayNight_nefsc == "day" ~ "mismatch", 
  )) %>%
  mutate(towTime = case_when(
    time_dif > 0 ~ "nefsc_first", 
    time_dif < 0 ~ "sf_first"
  )) %>%
  drop_na(AVGDEPTH, BOTTEMP, dayNight, towTime, mgmt_area) %>%
  distinct() 



###############################################################################
#observer 
#2mi and 48hrs
paired_tows_2mi_48hr_ob_re <- paired_tows_2mi_48hr_ob %>%
  filter(SVSPP == 73 & NESPP4 == 818 | #cod 
         SVSPP == 74 & NESPP4 == 1477 | #haddock
         SVSPP == 75 & NESPP4 == 2695 | #pollock
         SVSPP == 105 & NESPP4 == 1230 | #yellowtail flounder
         SVSPP == 102 & NESPP4 == 1240 | #american plaice
         SVSPP == 107 & NESPP4 == 1220 | #witch flounder
         SVSPP == 108 & NESPP4 == 1250 | #windowpane
         SVSPP == 106 & NESPP4 == 1200 | #winter flounder
         SVSPP == 155 & NESPP4 == 2400 | #acadian redfish
         SVSPP == 197 & NESPP4 == 124    #monkfish
        ) %>%
  drop_na(ob_species_cpua, nefsc_species_cpua) %>%
  filter(CATCHWT_updated > 0) %>%
  mutate(old_relative_efficiency = log(ob_species_cpua)/log(nefsc_species_cpua)) %>%
  mutate(relative_efficiency = nefsc_species_cpua/(nefsc_species_cpua + ob_species_cpua)) %>%
  mutate(mgmt_area = case_when(
    AREA.x %in% c(511, 512, 513, 514, 515) ~ "GOM", 
    AREA.x %in% c(521, 522, 526, 525, 561, 562, 551, 552) ~ "GB", 
    AREA.x %in% c(611, 612, 613, 539, 538, 537) ~ "SNE"
  )) %>%
  mutate(season = case_when(
    month(START_TOW_DATE_GMT) %in% c(03, 04, 05) ~ "Spring", 
    month(START_TOW_DATE_GMT) %in% c(09, 10, 11) ~ "Fall", 
  )) %>%
  mutate(DayNight = case_when(
    dayNight_ob == "night" & dayNight_nefsc == "night" ~ "Night",
    dayNight_ob == "day" & dayNight_nefsc == "day" ~ "Day",
    dayNight_ob == "night" & dayNight_nefsc =="day" ~ "Mismatch",
    dayNight_ob == "day" & dayNight_nefsc == "night" ~ "Mismatch"
  )) %>%
  mutate(towTime = case_when(
    time_dif > 0 ~ "nefsc_first", 
    time_dif < 0 ~ "sf_first"
  )) %>%
  mutate(trawl_type = as.factor(trawl_type)) %>%
  drop_na(trawl_type) %>%
  drop_na(AVGDEPTH, BOTTEMP, DayNight, towTime) %>%
  distinct()


#3mi and 72hrs
paired_tows_3mi_72hr_ob_re <- paired_tows_3mi_72hr_ob %>%
  filter(SVSPP == 73 & NESPP4 == 818 | #cod 
         SVSPP == 74 & NESPP4 == 1477 | #haddock
         SVSPP == 75 & NESPP4 == 2695 | #pollock
         SVSPP == 105 & NESPP4 == 1230 | #yellowtail flounder
         SVSPP == 102 & NESPP4 == 1240 | #american plaice
         SVSPP == 107 & NESPP4 == 1220 | #witch flounder
         SVSPP == 108 & NESPP4 == 1250 | #windowpane
         SVSPP == 106 & NESPP4 == 1200 | #winter flounder
         SVSPP == 155 & NESPP4 == 2400 | #acadian redfish
         SVSPP == 197 & NESPP4 == 124    #monkfish
        ) %>%
  drop_na(ob_species_cpua, nefsc_species_cpua) %>%
  filter(CATCHWT_updated > 0) %>%
  mutate(old_relative_efficiency = log(ob_species_cpua)/log(nefsc_species_cpua)) %>%
  mutate(relative_efficiency = nefsc_species_cpua/(nefsc_species_cpua + ob_species_cpua)) %>%
  mutate(mgmt_area = case_when(
    AREA.x %in% c(511, 512, 513, 514, 515) ~ "GOM", 
    AREA.x %in% c(521, 522, 526, 525, 561, 562, 551, 552) ~ "GB", 
    AREA.x %in% c(611, 612, 613, 539, 538, 537) ~ "SNE"
  )) %>%
  mutate(season = case_when(
    month(START_TOW_DATE_GMT) %in% c(03, 04, 05) ~ "Spring", 
    month(START_TOW_DATE_GMT) %in% c(09, 10, 11) ~ "Fall", 
  )) %>%
  mutate(DayNight = case_when(
    dayNight_ob == "night" & dayNight_nefsc == "night" ~ "Night",
    dayNight_ob == "day" & dayNight_nefsc == "day" ~ "Day",
    dayNight_ob == "night" & dayNight_nefsc =="day" ~ "Mismatch",
    dayNight_ob == "day" & dayNight_nefsc == "night" ~ "Mismatch"
  )) %>%
  mutate(towTime = case_when(
    time_dif > 0 ~ "nefsc_first", 
    time_dif < 0 ~ "sf_first"
  )) %>%
  mutate(trawl_type = as.factor(trawl_type)) %>%
  drop_na(trawl_type) %>%
  drop_na(AVGDEPTH, BOTTEMP, DayNight, towTime) %>%
  distinct()





```

# Species Datasets
```{r}
#creating a separate dataset for each species 
#STUDY FLEET
#2 mi and 48 hrs
#COD
cod_paired_tows_2mi_48hr_re <- paired_tows_2mi_48hr_re %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE)

#HADDOCK
haddock_paired_tows_2mi_48hr_re <- paired_tows_2mi_48hr_re %>%
  filter(SVSPP == 74 & SPECIES_ITIS == 164744) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE)

#WITCH FLOUNDER
witchfl_paired_tows_2mi_48hr_re <- paired_tows_2mi_48hr_re %>%
  filter(SVSPP == 107 & SPECIES_ITIS == 172873) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE)

#YELLLOWTAIL FLOUNDER
yellowtailfl_paired_tows_2mi_48hr_re <- paired_tows_2mi_48hr_re %>%
  filter(SVSPP == 105 & SPECIES_ITIS == 172909) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE)


#3 mi and 72 hrs
#COD
cod_paired_tows_3mi_72hr_re <- paired_tows_3mi_72hr_re %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE)

#HADDOCK
haddock_paired_tows_3mi_72hr_re <- paired_tows_3mi_72hr_re %>%
  filter(SVSPP == 74 & SPECIES_ITIS == 164744) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE)

#WITCH FLOUNDER
witchfl_paired_tows_3mi_72hr_re <- paired_tows_3mi_72hr_re %>%
  filter(SVSPP == 107 & SPECIES_ITIS == 172873) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE)

#YELLLOWTAIL FLOUNDER
yellowtailfl_paired_tows_3mi_72hr_re <- paired_tows_3mi_72hr_re %>%
  filter(SVSPP == 105 & SPECIES_ITIS == 172909) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE)




###############################################################################

#OBSERVER
#2 mi and 48 hrs
#COD
cod_paired_tows_2mi_48hr_ob_re <- paired_tows_2mi_48hr_ob_re %>%
  filter(SVSPP == 73 & NESPP4 == 818) %>% 
  distinct(trip_haul_ID, .keep_all = TRUE)

#YELLLOWTAIL FLOUNDER
yellowtailfl_paired_tows_2mi_48hr_ob_re <- paired_tows_2mi_48hr_ob_re %>%
  filter(SVSPP == 105 & NESPP4 == 1230) %>% 
  distinct(trip_haul_ID, .keep_all = TRUE)

#HADDOCK
haddock_paired_tows_2mi_48hr_ob_re <- paired_tows_2mi_48hr_ob_re %>%
  filter(SVSPP == 74 & NESPP4 == 1477) %>% 
  distinct(trip_haul_ID, .keep_all = TRUE)

#WITCH FLOUNDER
witchfl_paired_tows_2mi_48hr_ob_re <- paired_tows_2mi_48hr_ob_re %>%
  filter(SVSPP == 107 & NESPP4 == 1220) %>% 
  distinct(trip_haul_ID, .keep_all = TRUE)


#3 mi and 72 hrs
#COD
cod_paired_tows_3mi_72hr_ob_re <- paired_tows_3mi_72hr_ob_re %>%
  filter(SVSPP == 73 & NESPP4 == 818) %>% 
  distinct(trip_haul_ID, .keep_all = TRUE)

#HADDOCK
haddock_paired_tows_3mi_72hr_ob_re <- paired_tows_3mi_72hr_ob_re %>%
  filter(SVSPP == 74 & NESPP4 == 1477) %>% 
  distinct(trip_haul_ID, .keep_all = TRUE)

#WITCH FLOUNDER
witchfl_paired_tows_3mi_72hr_ob_re <- paired_tows_3mi_72hr_ob_re %>%
  filter(SVSPP == 107 & NESPP4 == 1220) %>% 
  distinct(trip_haul_ID, .keep_all = TRUE)

#YELLLOWTAIL FLOUNDER
yellowtailfl_paired_tows_3mi_72hr_ob_re <- paired_tows_3mi_72hr_ob_re %>%
  filter(SVSPP == 105 & NESPP4 == 1230) %>% 
  distinct(trip_haul_ID, .keep_all = TRUE)




```





# Study Fleet & NEFSC Pairs
## 2m and 48 hr Pairs 

### Cod
#### Exploratory Plots 
```{r}
#Looking at the cpua for the paired tows for each species 
cod_paired_tows_2mi_48hr_re %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua, fill = "Study Fleet"), stat = "identity") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua, fill = "NEFSC"), stat = "identity") + 
  labs(x = "Tow Number", y = CPUA_label, 
       title = "Comparison of CPUA for Atlantic Cod", 
       subtitle = "Pairs within 5 mi and 72 hrs") + 
  scale_fill_manual(name = "", 
                    values = c("Study Fleet" = "red", "NEFSC" = "blue"), 
                    labels = c("Study Fleet", "NEFSC")) + 
  theme_classic() + 
  theme(axis.text.x = element_blank())


#Looking at the relative efficiency of the study fleet tows compared to the nefsc survey 
cod_paired_tows_2mi_48hr_re %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 50, color = "black", fill = "white") + 
  geom_vline(aes(xintercept = 0.5),
            color = "black", linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = mean(relative_efficiency)),
            color = "red", linetype = "dashed", size = 1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Atlantic Cod", 
       subtitle = "Pairs within 5 mi and 72 hrs")


#map of the matched tows
cod_paired_tows_2mi_48hr_re %>%
  ggplot() + 
  geom_sf(data = nefsc_strata, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  geom_point(data = cod_paired_tows_2mi_48hr_re, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  geom_point(data = cod_paired_tows_2mi_48hr_re, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  
  # geom_segment(data = paired_tows_1mi_24hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
  #                                               y = START_TOW_LAT.x, yend = END_TOW_LAT.x)) +
  coord_sf(ylim = c(39, 44),  xlim = c(-74, -66)) + 
  scale_colour_manual("", breaks = c("Study Fleet", "NEFSC"), values = c("red", "blue")) +
  labs(title = "Study Fleet tows Matched to NEFSC tows for Cod", subtitle = "within 5 mi and 72 hrs")



#looking at scatterplot of CPUAs 
cod_paired_tows_2mi_48hr_re %>%
  ggplot(aes(x = sf_species_cpua, 
             y = nefsc_species_cpua)) + 
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  labs(x = 'Study Fleet CPUA', y = 'NEFSC CPUA', title = '')



```

#### T-test
```{r, message = FALSE, warning = FALSE}
#looking at the boxplot and histograms of the catch per unit area 
box.plot(cod_paired_tows_2mi_48hr_re)
hist_kh(cod_paired_tows_2mi_48hr_re)

#log-transforming the data
cod_paired_tows_2mi_48hr_re <- cod_paired_tows_2mi_48hr_re %>%
  mutate(diff = sf_species_cpua - nefsc_species_cpua,
         log_sf_species_cpua = log(sf_species_cpua), 
         log_nefsc_species_cpua = log(nefsc_species_cpua), 
         diff_of_logs = log_sf_species_cpua - log_nefsc_species_cpua)

#looking at the boxplot and histograms of the difference between CPUA
box.plot_diff(cod_paired_tows_2mi_48hr_re)
hist_kh_diff(cod_paired_tows_2mi_48hr_re)

#looking at the boxplot and histograms of the diff_of_logs
box.plot_diff_log(cod_paired_tows_2mi_48hr_re)
hist_kh_diff_log(cod_paired_tows_2mi_48hr_re)

#assumptions of normality and equal variance are met with the log transformed data, 
#so the t-test was conducted with the log-transformed data


#running t-test
cod_ttest_2mi48hr <- t.test(cod_paired_tows_2mi_48hr_re$log_sf_species_cpua, cod_paired_tows_2mi_48hr_re$log_nefsc_species_cpua, paired = TRUE)
cod_ttest_2mi48hr


#back transform the estimate
exp(cod_ttest_2mi48hr$estimate)
exp(cod_ttest_2mi48hr$conf.int)

```

#### Model Runs
```{r, message = FALSE, warning = FALSE}
#COD
codm_2mi48hr <- fit.models(cod_paired_tows_2mi_48hr_re)
compare.models(codm_2mi48hr)


#storing the optimal model and plotting the diagnostics
codm_optimal_2mi48hr <- glm(relative_efficiency ~ VESSEL_NAME +season + BOTTEMP + towTime, 
                    family = binomial, data = cod_paired_tows_2mi_48hr_re)

par(mfrow=c(2,2))
plot(codm_optimal_2mi48hr)


#back transform the estimates and CIs 
exp(cbind(OR = coef(codm_optimal_2mi48hr), confint(codm_optimal_2mi48hr)))

#look at the component residual plots 
crPlots(codm_optimal_2mi48hr)

# Extract the fitted and predicted values 
cod_paired_tows_2mi_48hr_re$predict <- predict(codm_optimal_2mi48hr)
cod_paired_tows_2mi_48hr_re$fitted <- fitted(codm_optimal_2mi48hr)

#predicted vs observed values 
cod_paired_tows_2mi_48hr_re %>%
  ggplot(aes(x = fitted, 
             y = relative_efficiency)) + 
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  xlim(0,1) + 
  ylim(0,1) + 
  labs(x = 'Predicted Values', y = 'Actual Values', title = 'Predicted vs. Actual Values')


#getting final RE estimate 
cod_paired_tows_2mi_48hr_re %>%
  group_by(VESSEL_NAME) %>%
  summarise(mean(fitted), n = n())

cod_paired_tows_2mi_48hr_re %>%
  summarise(mean(fitted), n = n())


cod_paired_tows_2mi_48hr_re %>%
  ggplot(aes(x = VESSEL_NAME, 
             y = fitted)) + 
  geom_jitter() + 
  stat_summary(
    geom = "point",
    fun = "mean",
    col = "black",
    size = 3,
    shape = 24,
    fill = "red"
  ) + 
  labs(x = "Vessel Name", y = "Fitted Values of Relative Efficiency") + 
  geom_hline(yintercept = 0.3600107, linetype = "dashed", color = "red") + 
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "black") + 
  coord_flip()


#now just selecting for the most efficient vessels and estimating the relative efficiency
cod_paired_tows_2mi_48hr_re %>%
  filter(VESSEL_NAME %in% c("ELIZABETH & KATHERINE", "LIGHTNING BAY", "LISA ANN II", "LISA ANN III", "MARY K")) %>%
  summarise(mean(fitted), n = n())
  

cod_paired_tows_2mi_48hr_re %>%
  filter(VESSEL_NAME %in% c("ELIZABETH & KATHERINE", "LIGHTNING BAY", "LISA ANN II", "LISA ANN III", "MARY K")) %>%
  ggplot(aes(x = VESSEL_NAME, 
             y = fitted)) + 
  geom_jitter() + 
  stat_summary(
    geom = "point",
    fun = "mean",
    col = "black",
    size = 3,
    shape = 24,
    fill = "red"
  ) + 
  labs(x = "Vessel Name", y = "Fitted Values of Relative Efficiency") + 
  ylim(0,1) + 
  geom_hline(yintercept = 0.1630779, linetype = "dashed", color = "red") + 
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "black") + 
  coord_flip()

#plotting effects of each variable on RE
plot(allEffects(codm_optimal))

#count of how many tows are more efficient than the survey 
cod_paired_tows_2mi_48hr_re %>%
  filter(relative_efficiency < 0.5) %>%
  count()


###############################################################################
# #predicted vs trawl type w point shape as explanatory variables - not important for this project but saving for my thesis work 
#mgmt_area
cod_paired_tows_2mi_48hr_re %>%
  ggplot(aes(x = VESSEL_NAME,
             y = fitted, color = mgmt_area)) +
  geom_jitter() +
  labs(x = "Vessel Name", y = "Fitted Values") +
  coord_flip()

#season
cod_paired_tows_2mi_48hr_re %>%
  ggplot(aes(x = VESSEL_NAME,
             y = fitted, color = season)) +
  geom_jitter() +
  coord_flip()

#depth
cod_paired_tows_2mi_48hr_re %>%
  ggplot(aes(x = VESSEL_NAME,
             y = fitted, color = BOTTEMP)) +
  geom_jitter() +
  coord_flip()

#MESH_TYPE
cod_paired_tows_2mi_48hr_re %>%
  ggplot(aes(x = VESSEL_NAME,
             y = fitted, color = as.factor(MESH_TYPE))) +
  geom_jitter() +
  coord_flip()


```




























## 3m and 72hr Pairs 

### Cod
#### Exploratory Plots 

```{r}

```

