---
title: "relative_efficiency_analysis"
output: html_document
date: "2022-08-17"
---


```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(skimr)
library(data.table)
library(fuzzyjoin)
library(lubridate)
library(kableExtra)

library(maps) # land masses
library(rgdal) # read OGR vector maps into Spatial objects
library(viridis) # for customizing scale bars
library(mapproj)
library(hexbin)
library(sf)
library(scales)
library(gridExtra)
library(beepr)
```


# Data for Maps 
```{r}
#Additional Data for Maps
#Statistical Areas
sareas <- st_read(dsn = "./data/Statistical_Areas_2010_withNames") %>%
  st_set_crs(4269)
sareas <- sareas %>% filter(Id %in% c("464", "465", "511", "512", "513", "514", "515", "521", "522", "525", "526", "537", "538", "539", "551", "561", "562", "611", "612", "613", "543", "542", "541", "534", "533", "616", "615", "614", "621", "622", "623", "624"))  
centroids <- sf::st_coordinates(st_centroid(sareas)) 
areas <- cbind(sareas, centroids)


#Land Mass
states <- map_data("state")
NEUS <- subset(states, region %in% c("Maine", "massachusetts", "new hampshire", "vermont", "maine", "rhode island",
                "connecticut","new york","new jersey","delaware","pennsylvania",
                            "maryland","virginia","north carolina","west virginia"))


#NEFSC Survey Strata
sf::sf_use_s2(FALSE)
nefsc_strata <- st_read(dsn = "./data/strata") %>%
  st_set_crs(4269)


```



# Study Fleet and NEFSC Pairs
## 1m and 24hr Paired Tows 
### Comparing CPUA and Relative Efficiency 
```{r}
#filtering for just the species of interest and creating a relative efficiency variable 
paired_tows_1mi_24hr_logre <- paired_tows_1mi_24hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712 | #cod 
         SVSPP == 74 & SPECIES_ITIS == 164744 | #haddock
         SVSPP == 75 & SPECIES_ITIS == 164727 | #pollock
         SVSPP == 105 & SPECIES_ITIS == 172909 | #yellowtail flounder
         SVSPP == 102 & SPECIES_ITIS == 172877 | #american plaice
         SVSPP == 107 & SPECIES_ITIS == 172873 | #witch flounder
         SVSPP == 76 & SPECIES_ITIS == 164732  | #white hake
         SVSPP == 108 & SPECIES_ITIS == 172746 | #windowpane
         SVSPP == 106 & SPECIES_ITIS == 172905 | #winter flounder
         SVSPP == 155 & SPECIES_ITIS == 166774 | #acadian redfish
         SVSPP == 101 & SPECIES_ITIS == 172933 | #atlantic halibut   #NE Groundfish spp

    
         SVSPP == 72 & SPECIES_ITIS == 164791 | #silver hake
         SVSPP == 77 & SPECIES_ITIS == 164730 | #red hake
         SVSPP == 78 & SPECIES_ITIS == 164731 | #spotted hake
           
         SVSPP == 103 & SPECIES_ITIS == 172735 | #summer flounder
         SVSPP == 104 & SPECIES_ITIS == 172739 | #fourspot flounder
    
         SVSPP == 197 & SPECIES_ITIS == 164499 | #goosefish
         SVSPP == 15 & SPECIES_ITIS == 160617    #spiny dogfish
        ) %>%
  drop_na(sf_species_cpua, nefsc_species_cpua) %>%
  mutate(relative_efficiency = log(sf_species_cpua)/log(nefsc_species_cpua)) %>%
  mutate(mgmt_area = case_when(
    AREA_CODE %in% c(511, 512, 513, 514, 515) ~ "GOM", 
    AREA_CODE %in% c(521, 522, 526, 525, 561, 562, 551, 552) ~ "GB", 
    AREA_CODE %in% c(611, 612, 613, 539, 538, 537) ~ "SNE"
  )) %>%
  distinct()
  # filter(SVSPP == 73)
  




#COD
#Looking at the cpua for the paired tows
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Atlantic Cod", 
       subtitle = "Pairs within 1 mi and 24 hrs")

#Looking at the relative efficiency of the study fleet catch to the science center survey 
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept=1),
            color="red", linetype="dashed", size=1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Atlantic Cod", 
       subtitle = "Pairs within 1 mi and 24 hrs")




#HADDOCK
#Looking at the cpua for the paired tows
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 74 & SPECIES_ITIS == 164744) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Haddock", 
       subtitle = "Pairs within 1 mi and 24 hrs")

#Looking at the relative efficiency of the study fleet catch to the science center survey 
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 74 & SPECIES_ITIS == 164744) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept=1),
            color="red", linetype="dashed", size=1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Haddock", 
       subtitle = "Pairs within 1 mi and 24 hrs")




#YELLOWTAIL FLOUNDER
#Looking at the cpua for the paired tows
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 105 & SPECIES_ITIS == 172909) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Yellowtail Flounder", 
       subtitle = "Pairs within 1 mi and 24 hrs")

#Looking at the relative efficiency of the study fleet catch to the science center survey 
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 105 & SPECIES_ITIS == 172909) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept=1),
            color="red", linetype="dashed", size=1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Yellowtail Flounder", 
       subtitle = "Pairs within 1 mi and 24 hrs")




#WINTER FLOUNDER
#Looking at the cpua for the paired tows
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 106 & SPECIES_ITIS == 172905) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Winter Flounder", 
       subtitle = "Pairs within 1 mi and 24 hrs")

#Looking at the relative efficiency of the study fleet catch to the science center survey 
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 106 & SPECIES_ITIS == 172905) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept=1),
            color="red", linetype="dashed", size=1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Winter Flounder", 
       subtitle = "Pairs within 1 mi and 24 hrs")




#MONKFISH
#Looking at the cpua for the paired tows
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 197 & SPECIES_ITIS == 164499) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Monkfish", 
       subtitle = "Pairs within 1 mi and 24 hrs")

#Looking at the relative efficiency of the study fleet catch to the science center survey 
paired_tows_1mi_24hr_logre %>%
  filter(SVSPP == 197 & SPECIES_ITIS == 164499) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept=1),
            color="red", linetype="dashed", size=1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Monkfish", 
       subtitle = "Pairs within 1 mi and 24 hrs")


```


### Maps of Matched Tows 
```{r}
#plotting the matches for 1 mile and 24 hrs w Stat Areas
paired_tows_1mi_24hr %>%
  ggplot() + 
  geom_sf(data = areas, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  geom_point(data = paired_tows_1mi_24hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  geom_point(data = paired_tows_1mi_24hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  
  # geom_segment(data = paired_tows_1mi_24hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
  #                                               y = START_TOW_LAT.x, yend = END_TOW_LAT.x)) +
  coord_sf(ylim = c(39, 44),  xlim = c(-74, -66)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue")) +
  labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 1 mi and 24 hrs")
```




## 5m and 72hr Paired Tows
### Comparing CPUA and Relative Efficiency 
```{r}
#filtering for just the species of interest and creating a relative efficiency variable 
paired_tows_5mi_72hr_logre <- paired_tows_5mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712 | #cod 
         SVSPP == 74 & SPECIES_ITIS == 164744 | #haddock
         SVSPP == 75 & SPECIES_ITIS == 164727 | #pollock
         SVSPP == 105 & SPECIES_ITIS == 172909 | #yellowtail flounder
         SVSPP == 102 & SPECIES_ITIS == 172877 | #american plaice
         SVSPP == 107 & SPECIES_ITIS == 172873 | #witch flounder
         SVSPP == 76 & SPECIES_ITIS == 164732  | #white hake
         SVSPP == 108 & SPECIES_ITIS == 172746 | #windowpane
         SVSPP == 106 & SPECIES_ITIS == 172905 | #winter flounder
         SVSPP == 155 & SPECIES_ITIS == 166774 | #acadian redfish
         SVSPP == 101 & SPECIES_ITIS == 172933 | #atlantic halibut   #NE Groundfish spp

    
         SVSPP == 72 & SPECIES_ITIS == 164791 | #silver hake
         SVSPP == 77 & SPECIES_ITIS == 164730 | #red hake
         SVSPP == 78 & SPECIES_ITIS == 164731 | #spotted hake
           
         SVSPP == 103 & SPECIES_ITIS == 172735 | #summer flounder
         SVSPP == 104 & SPECIES_ITIS == 172739 | #fourspot flounder
    
         SVSPP == 197 & SPECIES_ITIS == 164499 | #goosefish
         SVSPP == 15 & SPECIES_ITIS == 160617    #spiny dogfish
        ) %>%
  drop_na(sf_species_cpua, nefsc_species_cpua) %>%
  mutate(relative_efficiency = log(sf_species_cpua)/log(nefsc_species_cpua)) %>%
  mutate(mgmt_area = case_when(
    AREA_CODE %in% c(511, 512, 513, 514, 515) ~ "GOM", 
    AREA_CODE %in% c(521, 522, 526, 525, 561, 562, 551, 552) ~ "GB", 
    AREA_CODE %in% c(611, 612, 613, 539, 538, 537) ~ "SNE"
  )) %>%
  distinct() 




#COD
#Looking at the cpua for the paired tows for each species 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  filter(sf_species_cpua < 2000) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Atlantic Cod", 
       subtitle = "Pairs within 5 mi and 72 hrs")

#Looking at the relative efficiency of the study fleet tows compared to the nefsc survey 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept = 1),
            color = "black", linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = mean(relative_efficiency)),
            color = "red", linetype = "dashed", size = 1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Atlantic Cod", 
       subtitle = "Pairs within 5 mi and 72 hrs")




#HADDOCK
#Looking at the cpua for the paired tows for each species 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 74 & SPECIES_ITIS == 164744) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  filter(sf_species_cpua < 2000) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Haddock", 
       subtitle = "Pairs within 5 mi and 72 hrs")

#Looking at the relative efficiency of the study fleet tows compared to the nefsc survey 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 74 & SPECIES_ITIS == 164744) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept = 1),
            color = "black", linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = mean(relative_efficiency)),
            color = "red", linetype = "dashed", size = 1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Haddock", 
       subtitle = "Pairs within 5 mi and 72 hrs")




#WITCH FLOUNDER 
#Looking at the cpua for the paired tows for each species 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 107 & SPECIES_ITIS == 172873) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  filter(sf_species_cpua < 2000) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Witch Flounder", 
       subtitle = "Pairs within 5 mi and 72 hrs")

#Looking at the relative efficiency of the study fleet tows compared to the nefsc survey 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 107 & SPECIES_ITIS == 172873) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept = 1),
            color = "black", linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = mean(relative_efficiency)),
            color = "red", linetype = "dashed", size = 1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Witch Flounder", 
       subtitle = "Pairs within 5 mi and 72 hrs")




#YELLOWTAIL FLOUNDER
#Looking at the cpua for the paired tows for each species 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 105 & SPECIES_ITIS == 172909) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  filter(sf_species_cpua < 2000) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Yellowtail Flounder", 
       subtitle = "Pairs within 5 mi and 72 hrs")

#Looking at the relative efficiency of the study fleet tows compared to the nefsc survey 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 105 & SPECIES_ITIS == 172909) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept = 1),
            color = "black", linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = mean(relative_efficiency)),
            color = "red", linetype = "dashed", size = 1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Yellowtail Flounder", 
       subtitle = "Pairs within 5 mi and 72 hrs")




#AMERICAN PLAICE
#Looking at the cpua for the paired tows for each species 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 102 & SPECIES_ITIS == 172877) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  filter(sf_species_cpua < 2000) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for American Plaice", 
       subtitle = "Pairs within 5 mi and 72 hrs")

#Looking at the relative efficiency of the study fleet tows compared to the nefsc survey 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 102 & SPECIES_ITIS == 172877) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept = 1),
            color = "black", linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = mean(relative_efficiency)),
            color = "red", linetype = "dashed", size = 1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for American Plaice", 
       subtitle = "Pairs within 5 mi and 72 hrs")




#WINTER FLOUNDER
#Looking at the cpua for the paired tows for each species 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 106 & SPECIES_ITIS == 172905) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  filter(sf_species_cpua < 2000) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Winter Flounder", 
       subtitle = "Pairs within 5 mi and 72 hrs")

#Looking at the relative efficiency of the study fleet tows compared to the nefsc survey 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 106 & SPECIES_ITIS == 172905) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept = 1),
            color = "black", linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = mean(relative_efficiency)),
            color = "red", linetype = "dashed", size = 1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Winter Flounder", 
       subtitle = "Pairs within 5 mi and 72 hrs")




#MONKFISH
#Looking at the cpua for the paired tows for each species 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 197 & SPECIES_ITIS == 164499) %>% 
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  filter(sf_species_cpua < 2000) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue") + 
  labs(x = "Tow Number", y = "CPUA (lbs/km2)", 
       title = "Comparison of CPUA for Monkfish", 
       subtitle = "Pairs within 5 mi and 72 hrs") 

#Looking at the relative efficiency of the study fleet tows compared to the nefsc survey 
paired_tows_5mi_72hr_logre %>%
  filter(SVSPP == 197 & SPECIES_ITIS == 164499) %>%
  distinct(EFFORT_ID, .keep_all = TRUE) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept = 1),
            color = "black", linetype = "dashed", size = 1) + 
  geom_vline(aes(xintercept = mean(relative_efficiency)),
            color = "red", linetype = "dashed", size = 1) + 
  labs(x = "Relative Efficiency", y = "Count", 
       title = "Histogram of Relative Efficiency for Monkfish", 
       subtitle = "Pairs within 5 mi and 72 hrs")

  
```


### Maps of Matched Tows 
```{r}
#plotting the matches for 5 mi and 3 days 
paired_tows_5mi_72hr %>%
  ggplot() + 
  geom_sf(data = areas, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  
  # geom_segment(data = paired_tows_1mi_24hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
  #                                               y = START_TOW_LAT.x, yend = END_TOW_LAT.x)) +
  coord_sf(ylim = c(39, 44),  xlim = c(-74, -66)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue")) +
  labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 5 mi and 72 hrs")



#Zooming in on the GOM and looking at tow length for 5mi and 3 day matches 
paired_tows_5mi_72hr %>%
  ggplot() + 
  geom_sf(data = areas, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
                                                y = START_TOW_LAT.x, yend = END_TOW_LAT.x, color = "NEFSC")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.y, xend = END_TOW_LON.y,
                                                y = START_TOW_LAT.y, yend = END_TOW_LAT.y, color = "Study Fleet")) +
  coord_sf(ylim = c(41.9, 43.3),  xlim = c(-71, -69.6)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue"))
# labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 5 mi and 72 hrs")



#Zooming in on the GB and looking at tow length for 5mi and 3 day matches 
paired_tows_5mi_72hr %>%
  ggplot() + 
  geom_sf(data = areas, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
                                                y = START_TOW_LAT.x, yend = END_TOW_LAT.x, color = "NEFSC")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.y, xend = END_TOW_LON.y,
                                                y = START_TOW_LAT.y, yend = END_TOW_LAT.y, color = "Study Fleet")) +
  coord_sf(ylim = c(40.5, 42.5),  xlim = c(-69.6, -66)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue"))
# labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 5 mi and 72 hrs")



#Zooming in on the SNE and looking at tow length for 5mi and 3 day matches 
paired_tows_5mi_72hr %>%
  ggplot() + 
  geom_sf(data = areas, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
                                                y = START_TOW_LAT.x, yend = END_TOW_LAT.x, color = "NEFSC")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.y, xend = END_TOW_LON.y,
                                                y = START_TOW_LAT.y, yend = END_TOW_LAT.y, color = "Study Fleet")) +
  coord_sf(ylim = c(39.5, 41.5),  xlim = c(-72.2, -70.2)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue"))
# labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 5 mi and 72 hrs")





################################################################################
#Same plots but with nefsc survey strata instead of stat atea 

paired_tows_5mi_72hr %>%
  ggplot() + 
  geom_sf(data = nefsc_strata, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  
  # geom_segment(data = paired_tows_1mi_24hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
  #                                               y = START_TOW_LAT.x, yend = END_TOW_LAT.x)) +
  coord_sf(ylim = c(39, 44),  xlim = c(-74, -66)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue")) +
  labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 5 mi and 72 hrs")



#Zooming in on the GOM and looking at tow length for 5mi and 3 day matches 
paired_tows_5mi_72hr %>%
  ggplot() + 
  geom_sf(data = nefsc_strata, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
                                                y = START_TOW_LAT.x, yend = END_TOW_LAT.x, color = "NEFSC")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.y, xend = END_TOW_LON.y,
                                                y = START_TOW_LAT.y, yend = END_TOW_LAT.y, color = "Study Fleet")) +
  coord_sf(ylim = c(41.9, 43.3),  xlim = c(-71, -69.6)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue"))
# labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 5 mi and 72 hrs")



#Zooming in on the GB and looking at tow length for 5mi and 3 day matches 
paired_tows_5mi_72hr %>%
  ggplot() + 
  geom_sf(data = nefsc_strata, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
                                                y = START_TOW_LAT.x, yend = END_TOW_LAT.x, color = "NEFSC")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.y, xend = END_TOW_LON.y,
                                                y = START_TOW_LAT.y, yend = END_TOW_LAT.y, color = "Study Fleet")) +
  coord_sf(ylim = c(40.5, 42.5),  xlim = c(-69.6, -66)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue"))
# labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 5 mi and 72 hrs")



#Zooming in on the SNE and looking at tow length for 5mi and 3 day matches 
paired_tows_5mi_72hr %>%
  ggplot() + 
  geom_sf(data = nefsc_strata, fill = "grey") +
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  
               color="black",inherit.aes = FALSE)  +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.x,y = END_TOW_LAT.x, color = "NEFSC")) +
  # geom_point(data = paired_tows_5mi_72hr, aes(x = END_TOW_LON.y,y = END_TOW_LAT.y, color = "Study Fleet")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.x, xend = END_TOW_LON.x,
                                                y = START_TOW_LAT.x, yend = END_TOW_LAT.x, color = "NEFSC")) +
  geom_segment(data = paired_tows_5mi_72hr, aes(x = START_TOW_LON.y, xend = END_TOW_LON.y,
                                                y = START_TOW_LAT.y, yend = END_TOW_LAT.y, color = "Study Fleet")) +
  coord_sf(ylim = c(39.5, 41.5),  xlim = c(-72.2, -70.2)) + 
  scale_colour_manual("", breaks = c("NEFSC", "Study Fleet"), values = c("red", "blue"))
# labs(title = "Study Fleet tows Matched to NEFSC tows", subtitle = "within 5 mi and 72 hrs")
```


# Observer and NEFSC Pairs
```{r}

```












```{r}
##just me trying out different code













p2 %>%
  drop_na(nefsc_species_cpua, sf_species_cpua) %>%
  filter(SVSPP == 73) %>%
  ggplot() + 
  geom_histogram(aes(x = nefsc_species_cpua, fill = "blue", alpha=0.4, bins = 30)) + 
  geom_histogram(aes(x = sf_species_cpua, fill = "red", alpha=0.4, bins = 30)) + 
  xlim(0, 2000)






#looking at the differences in efficiency between the bigelow and the stuff fleet
#COD
g1 <- p2 %>%
  drop_na(nefsc_species_cpua, sf_species_cpua) %>%
  filter(SVSPP == 73) %>%
  ggplot() + 
  geom_histogram(aes(x = nefsc_species_cpua, fill = "blue")) + 
  xlim(0,2000)
  
  
g2 <-  p2 %>%
  drop_na(nefsc_species_cpua, sf_species_cpua) %>%
  filter(SVSPP == 73) %>%
  ggplot() + 
  geom_histogram(aes(x = sf_species_cpua, fill = "red")) + 
  xlim(0,2000)

grid.arrange(g1, g2)


#HADDOCK 
g1 <- p2 %>%
  drop_na(nefsc_species_cpua, sf_species_cpua) %>%
  filter(SVSPP == 74) %>%
  ggplot() + 
  geom_histogram(aes(x = nefsc_species_cpua, fill = "blue")) + 
  xlim(0,2000)
  
  
g2 <-  p2 %>%
  drop_na(nefsc_species_cpua, sf_species_cpua) %>%
  filter(SVSPP == 74) %>%
  ggplot() + 
  geom_histogram(aes(x = sf_species_cpua, fill = "red")) + 
  xlim(0,2000)

grid.arrange(g1, g2)



#YELLOWTAIL
g1 <- p2 %>%
  drop_na(nefsc_species_cpua, sf_species_cpua) %>%
  filter(SVSPP == 74) %>%
  ggplot() + 
  geom_histogram(aes(x = nefsc_species_cpua, fill = "blue")) + 
  xlim(0,2000)
  
  
g2 <-  p2 %>%
  drop_na(nefsc_species_cpua, sf_species_cpua) %>%
  filter(SVSPP == 74) %>%
  ggplot() + 
  geom_histogram(aes(x = sf_species_cpua, fill = "red")) + 
  xlim(0,2000)

grid.arrange(g1, g2)




#COD
paired_tows_5mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% #cod
  ggplot() + 
  geom_histogram(aes(x = sf_species_cpua, y = ..density..), fill = "red", bins = 100) + 
  # geom_label(aes(x = 7, y = 0.4, label = "Study Fleet CPUE"), color = "red") + 
  geom_histogram(aes(x = nefsc_species_cpua, y = -..density..), fill = "blue", bins = 100) + 
  # geom_label(aes(x = 7, y = -0.4, label = "NEFSC CPUE"), color = "blue") + 
  labs(x = "CPUA (lb/min)", y = "Density", 
       title = "Histogram of CPUE for Atlantic Cod", 
       subtitle = "Pairs within 5 mi and 72 hrs") + 
  xlim(0,2000)

#COD but log(CPUA)
paired_tows_5mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% #cod
  mutate(log_sf_species_cpua = log(sf_species_cpua)) %>%
  mutate(log_nefsc_species_cpua = log(nefsc_species_cpua)) %>%
  ggplot() + 
  geom_histogram(aes(x = log_sf_species_cpua, y = ..density..), fill = "red", bins = 100) + 
  # geom_label(aes(x = 7, y = 0.4, label = "Study Fleet CPUE"), color = "red") + 
  geom_histogram(aes(x = log_nefsc_species_cpua, y = -..density..), fill = "blue", bins = 100) + 
  # geom_label(aes(x = 7, y = -0.4, label = "NEFSC CPUE"), color = "blue") + 
  labs(x = "CPUA (lb/min)", y = "Density", 
       title = "Histogram of ln(CPUE) for Atlantic Cod", 
       subtitle = "Pairs within 5 mi and 72 hrs")






#HADDOCK
paired_tows_5mi_72hr %>%
  filter(SVSPP == 74 & SPECIES_ITIS == 164744) %>% #haddock
  ggplot() + 
  geom_histogram(aes(x = sf_species_cpua, y = ..density..), fill = "red", bins = 50) + 
  # geom_label(aes(x = 7, y = 0.4, label = "Study Fleet CPUE"), color = "red") + 
  geom_histogram(aes(x = nefsc_species_cpua, y = -..density..), fill = "blue", bins = 50) + 
  # geom_label(aes(x = 7, y = -0.4, label = "NEFSC CPUE"), color = "blue") + 
  labs(x = "CPUA (lb / km2)", y = "Density", 
       title = "Histogram of CPUE for Haddock", 
       subtitle = "Pairs within 5 mi and 72 hrs") + 
  xlim(0,2000)


#YELLOWTAIL
paired_tows_5mi_72hr %>%
  filter(SVSPP == 105 & SPECIES_ITIS == 172909) %>% #yellowtail
  ggplot() + 
  geom_histogram(aes(x = sf_species_cpua, y = ..density..), fill = "red", bins = 50) + 
  # geom_label(aes(x = 7, y = 0.4, label = "Study Fleet CPUE"), color = "red") + 
  geom_histogram(aes(x = nefsc_species_cpua, y = -..density..), fill = "blue", bins = 50) + 
  # geom_label(aes(x = 7, y = -0.4, label = "NEFSC CPUE"), color = "blue") + 
  labs(x = "CPUA (lb / km2)", y = "Density", 
       title = "Histogram of CPUE for Yellowtail", 
       subtitle = "Pairs within 5 mi and 72 hrs") + 
  xlim(0,2000)

#WINTER FLOUNDER
paired_tows_5mi_72hr %>%
  filter(SVSPP == 106 & SPECIES_ITIS == 172905) %>% #winter flounder
  ggplot() + 
  geom_histogram(aes(x = sf_species_cpua, y = ..density..), fill = "red", bins = 100) + 
  # geom_label(aes(x = 7, y = 0.4, label = "Study Fleet CPUE"), color = "red") + 
  geom_histogram(aes(x = nefsc_species_cpua, y = -..density..), fill = "blue", bins = 100) + 
  # geom_label(aes(x = 7, y = -0.4, label = "NEFSC CPUE"), color = "blue") + 
  labs(x = "CPUA (lb / km2)", y = "Density", 
       title = "Histogram of CPUE for Winter Flounder", 
       subtitle = "Pairs within 5 mi and 72 hrs") + 
  xlim(0,2000)


#MONKFISH
paired_tows_5mi_72hr %>%
  filter(SVSPP == 197 & SPECIES_ITIS == 164499) %>% #monkfish
  ggplot() + 
  geom_histogram(aes(x = sf_species_cpua, y = ..density..), fill = "red", bins = 100) + 
  # geom_label(aes(x = 7, y = 0.4, label = "Study Fleet CPUE"), color = "red") + 
  geom_histogram(aes(x = nefsc_species_cpua, y = -..density..), fill = "blue", bins = 100) + 
  # geom_label(aes(x = 7, y = -0.4, label = "NEFSC CPUE"), color = "blue") + 
  labs(x = "CPUA (lb/min)", y = "Density", 
       title = "Histogram of CPUE for Monkfish", 
       subtitle = "Pairs within 5 mi and 72 hrs") + 
  xlim(0,2000)


#AMERICAN PLAICE






###############################################################################
paired_tows_5mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% #cod
  ggplot(aes(y = log(sf_species_cpua))) + 
  geom_bar(stat = "identity", position = "identity")


paired_tows_5mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% 
  select(sf_species_cpua, )


paired_tows_5mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% 
  filter(sf_species_cpua < 2000) %>%
  filter(nefsc_species_cpua < 2000) %>%
  ggplot() + 
  geom_bar(aes(x = EFFORT_ID, y = sf_species_cpua), stat = "identity", fill = "red") + 
  geom_bar(aes(x = EFFORT_ID, y = -nefsc_species_cpua), stat = "identity", fill = "blue")



paired_tows_5mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>% 
  drop_na(sf_species_cpua, nefsc_species_cpua) %>%
  mutate(relative_efficiency = log(sf_species_cpua)/log(nefsc_species_cpua)) %>%
  ggplot() +
  geom_histogram(aes(x = relative_efficiency), bins = 100, color = "black", fill = "white") + 
  xlim(0, 4) + 
  geom_vline(aes(xintercept=1),
            color="red", linetype="dashed", size=1)




paired_tows_5mi_72hr %>%
  filter(SVSPP == 73 & SPECIES_ITIS == 164712) %>%
  select(nefsc_species_cpua, sf_species_cpua) %>%
  pivot_longer(cols = c("nefsc_species_cpua", "sf_species_cpua"), 
               names_to = "trawl_type", 
               values_to = "cpua")

  






  count(sf_species_cpua)
  

  
  
```

